##
# Separate server for exposing Nginx's status.
# This server listen on a port that should not be accessible from outside!
##
server {

    listen 8080;

    location /status/prometheus {
        vhost_traffic_status_display;
        vhost_traffic_status_display_format prometheus;
    }

}
